apiVersion: v1
kind: Service
metadata:
  name: jssip-svc
  labels:
    app: jssip
  namespace: asterix
spec:
  type: NodePort
  selector:
    app: jssip
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30012
