apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-08-07T09:50:27Z"
  generation: 1
  labels:
    app: jssip
  name: jssip
  namespace: asterix
  resourceVersion: "18842"
  uid: da07d2a7-1121-4974-a2c8-dbb92593dbcb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jssip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jssip
    spec:
      containers:
      - image: spreed/webrtc:latest
        imagePullPolicy: IfNotPresent
        name: jssip
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-07T09:50:39Z"
    lastUpdateTime: "2022-08-07T09:50:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-07T09:50:30Z"
    lastUpdateTime: "2022-08-07T09:50:39Z"
    message: ReplicaSet "jssip-b94b9d69d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
